{{- if eq (index .Values "nginx-ysoftman" "enabled") true }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ index .Values "nginx-ysoftman" "name" }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.common.server }}
    namespace: {{ index .Values "nginx-ysoftman" "name" }}
  project: {{ .Values.common.project }}
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: {{ index .Values "nginx-ysoftman" "source" "repoURL" }}
    path: {{ index .Values "nginx-ysoftman" "source" "path" }}
    targetRevision: {{ index .Values "nginx-ysoftman" "source" "targetRevision" }}
    helm:
      releaseName: {{ index .Values "nginx-ysoftman" "name" }}
      valueFiles: {{ index .Values "nginx-ysoftman" "valueFiles" }}
      values: |
        {{ toYaml (index .Values "nginx-ysoftman" "values") | nindent 8 }}
{{- end }}
