common:
  project: default
  server: https://kubernetes.default.svc

nginx-ysoftman:
  enabled: true
  name: nginx-ysoftman
  source:
    repoURL: https://github.com/ysoftman/test_code
    path: helm/charts/nginx-ysoftman
    targetRevision: HEAD
  valueFiles:
    - values-ysoftman.yaml
  values:
    test1: test1
