common:
  project: default
  server: https://kubernetes.default.svc

ysoftman-app1:
  enabled: true
  name: ysoftman-app1
  source:
    repoURL: https://github.com/ysoftman/test_code
    path: helm/charts/ysoftman-app1
    targetRevision: HEAD
  valueFiles:
    - values.yaml
  values:
    test1: test1
